Temp service dep
Simba-Avionic/deployment pull request #8
Opened 2024-03-13 14:58 UTC by Mateusz-Krajewski

2024-03-13 16:11 UTC, Mateusz-Krajewski reviewed
ok

2024-04-10 15:40 UTC, bartoszsnieg requested changes

2024-04-10 15:40 UTC, bartoszsnieg commented on mw/temp/config.json
> +      "/sys/bus/w1/devices/28-00000f88f767": 1
co oznaczają  te 0 i 1 ?

2024-04-10 15:40 UTC, bartoszsnieg commented on mw/temp/app.json
> +            "log_mode": "kConsole|kDLT"
Bezk kConsole

2024-04-28 08:08 UTC, closed without merging